version: "0.0.1"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  sidekiq-1st-instance:
    build:
      dockerfile: Dockerfile
    command: ./bin/container/run ./app/config/sidekiq/1st_instance.yml
    container_name: sidekiq-1st-instance
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  sidekiq-2nd-instance:
    build:
      dockerfile: Dockerfile
    command: ./bin/container/run ./app/config/sidekiq/2nd_instance.yml
    container_name: sidekiq-2nd-instance
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  sidekiq-3rd-instance:
    build:
      dockerfile: Dockerfile
    command: ./bin/container/run ./app/config/sidekiq/3rd_instance.yml
    container_name: sidekiq-3rd-instance
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  ui:
    build:
      dockerfile: Dockerfile
    command: bundle exec rackup --host 0.0.0.0
    container_name: ui
    ports:
      - "9292:9292"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - sidekiq-1st-instance
      - sidekiq-2nd-instance
      - sidekiq-3rd-instance

