apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sidekiq
  labels:
    app: sidekiq
spec:
  serviceName: sidekiq
  replicas: 6
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq-container
          image: mersen1/sidekiq-without-rails:latest
          env:
            - name: REDIS_URL
              value: "redis-cluster-$(HOSTNAME).redis-cluster:6379"
            - name: SIDEKIQ_CONCURRENCY
              value: "5"
          command: ["./bin/run", "./app/config/sidekiq/k8s.yml"]
