apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-deployment
  labels:
    app: sidekiq-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq-container
          image: mersen1/sidekiq-without-rails
          env:
            - name: REDIS_NODES
              value: |
                redis-cluster-0.redis-cluster:6379
                redis-cluster-1.redis-cluster:6379
                redis-cluster-2.redis-cluster:6379
                redis-cluster-3.redis-cluster:6379
                redis-cluster-4.redis-cluster:6379
                redis-cluster-5.redis-cluster:6379
            - name: SIDEKIQ_CONCURRENCY
              value: "5"
          command: ["./bin/run", "./app/config/sidekiq/k8s.yml"]
