apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-deployment
  labels:
    app: sidekiq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: mersen1/sidekiq-without-rails
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: SIDEKIQ_CONCURRENCY
              value: "5"
          ports:
            - containerPort: 9292
          command: ["./bin/container/run", "./app/config/sidekiq/1st_instance.yml"]
---
apiVersion: v1
kind: Service
metadata:
  name: sidekiq-service
spec:
  selector:
    app: sidekiq
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292
