apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: mersen1/sidekiq-without-rails
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379"
          ports:
            - containerPort: 9292
          command: ["bundle", "exec", "rackup", "--host", "0.0.0.0"]
          livenessProbe:
            httpGet:
              path: /
              port: 9292
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9292

