apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui-deployment
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      containers:
        - name: ui-deployment
          image: mersen1/sidekiq-without-rails
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379"
          ports:
            - containerPort: 9292
          command: ["bundle", "exec", "rackup", "--host", "0.0.0.0"]
          livenessProbe:
            httpGet:
              path: /
              port: 9292
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9292
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
spec:
  ingressClassName: "nginx"
  rules:
    - host: "localhost"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 80
