apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ui
  labels:
    app: ui
spec:
  serviceName: ui
  replicas: 6
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: mersen1/sidekiq-without-rails:latest
          env:
            - name: REDIS_URL
              value: "redis-cluster-$(HOSTNAME).redis-cluster:6379"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9292
          command: ["sh", "-c", "bundle exec rackup --host $POD_IP --port 9292"]
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9292
