apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: mersen1/sidekiq-without-rails
          env:
            - name: REDIS_NODES
              value: |
                redis-cluster-0.redis-cluster:6379
                redis-cluster-1.redis-cluster:6379
                redis-cluster-2.redis-cluster:6379
                redis-cluster-3.redis-cluster:6379
                redis-cluster-4.redis-cluster:6379
                redis-cluster-5.redis-cluster:6379
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9292
          command: ["bundle", "exec", "rackup", "--host", "$(POD_IP)"]
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9292
